### ISSUE TITLE
Getting auth error

### ISSUE THREAD

**Issue by gkarthiks** [bostrt/homebridge-bali-blinds#7] opened 2023-04-12 20:47 UTC
**Describe The Bug:**

Getting an auth issue during the startup of the bridge.

**To Reproduce:**
Install the plugin and provide the creds, restart the bridge.

**Logs:**

```
[12/04/2023, 15:43:39] [BaliBlinds] Error: Request failed. 401, body: WWW-Authenticate: MMSAuth error="invalid session"
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-bali-blinds/src/helper.ts:16:20)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Plugin Config:**

```json
        {
            "baliUsername": "<username>",
            "baliPassword": "<password>",
            "lowBattery": 33,
            "platform": "BaliBlinds"
        }
```

* **Plugin Version**: homebridge-bali-blinds v0.0.2-beta.0
* **Homebridge Version**: 1.5.1
* **Node.js Version**: v18.12.1
* **NPM Version**: 8.19.2
* **Operating System**:  hb-service

**Comment by bostrt** [comment] 2023-04-12 22:52
Thanks for the bug report! I'll take a look

**Comment by bostrt** [comment] 2023-04-13 00:26
Can you give this a try and run from a Linux machine (same place you are hosting homebridge is okay) and send me the output. It shouldn't log any credentials but please double-check before posting:

```
$ wget https://gist.githubusercontent.com/bostrt/714b4aebf57573cfc3c91c44debd4fc4/raw/7b264bac6f3fedb54f6832acee8c3fd8d0272cb1/bali-auth-test.sh
$ chmod +x bali-auth-test.sh
$ ./bali-auth-test.sh YOUR_USERNAME YOUR_PASSWORD
```

**Comment by bostrt** [comment] 2023-11-17 21:32
Closing this since I am unable to reproduce the issue. @gkarthiks if you still see this issue in the latest release please reopen this ticket.
https://github.com/bostrt/homebridge-bali-blinds/releases/tag/v0.0.5-beta.2

**Closed as completed by bostrt** 2023-11-17 21:32 UTC
Labels: bug
